### ISSUE TITLE
Microsoft Edge Chromium support

### ISSUE THREAD

**Issue by edwinbz** [ianramzy/decentralized-video-chat#43] opened 2020-04-27 16:46 UTC
Does not work in Microsoft Edge Chromium

**Comment by ianramzy** [comment] 2020-04-27 21:03
Can you please reply with your OS, browser version, and copy and paste the browser console logs when you try and call. (found by pressing F12)

**Comment by edwinbz** [comment] 2020-04-27 22:48
I have given the camera and microphone permissions and it shows a message "No webcam imput" on Microsoft Edge stable version (https://www.microsoft.com/en-us/edge)

![image](https://user-images.githubusercontent.com/23442979/80428129-c50ef400-88ae-11ea-8813-7d98ff1de048.png)

My environment: 
- Microsoft Windows 10 Pro [Versión 10.0.18363.815]
- Microsotf Edge Version 81.0.416.64 (Official Compilation) (64 bit)

Console logs:
[Infracción] Forced reflow while executing JavaScript took 48ms
chat.js:348 requestMediaStream
chat.js:348 DOMException: Requested device not found
chat.js:348 Failed to get local webcam video, check webcam privacy settings
chat.js:348 requestMediaStream
chat.js:348 DOMException: Requested device not found
chat.js:348 Failed to get local webcam video, check webcam privacy settings
chat.js:348 requestMediaStream
chat.js:348 DOMException: Requested device not found
chat.js:348 Failed to get local webcam video, check webcam privacy settings
chat.js:348 requestMediaStream
chat.js:348 DOMException: Requested device not found
chat.js:348 Failed to get local webcam video, check webcam privacy settings
chat.js:348 requestMediaStream
chat.js:348 DOMException: Requested device not found
chat.js:348 Failed to get local webcam video, check webcam privacy settings
chat.js:348 requestMediaStream
chat.js:348 DOMException: Requested device not found
chat.js:348 Failed to get local webcam video, check webcam privacy settings
chat.js:348 requestMediaStream
chat.js:348 DOMException: Requested device not found
chat.js:348 Failed to get local webcam video, check webcam privacy settings
chat.js:348 requestMediaStream
chat.js:348 DOMException: Requested device not found
chat.js:348 Failed to get local webcam video, check webcam privacy settings

**Comment by ianramzy** [comment] 2020-04-28 15:45
It is failing to get the webcam input. Do you have a webcam on your computer?

**Comment by edwinbz** [comment] 2020-04-29 04:07
Yes, on other sites it works correctly for me like this https://webcamtoy.com/es/

**Comment by NogrTL** [comment] 2020-05-13 10:20
Same...Oddly it's not even asking permissions for it when you set it to "Ask"

**Comment by Chaphasilor** [comment] 2020-05-31 14:30
Strange, I've been using this on Chromium Edge from the start, had no issues at all. I'm using the dev build, but all those features should be in the stable build as well.
Is it still not working for you guys?

**Comment by prediscover** [comment] 2020-06-09 07:48
works on macos 10.15.5 on Edge beta 83

**Comment by amadeobrands** [comment] 2020-06-17 14:09
Please just stop using Microsoft products 📦

**Comment by edwinbz** [comment] 2020-06-17 15:01
Github is a Microsoft Product 😅

**Comment by ianramzy** [comment] 2020-06-17 15:12
Y'all savage lmao @amadeobrands @edwinbz

**Comment by Chaphasilor** [comment] 2020-06-19 18:43
Sooo.... is this issue still a thing? xD

**Comment by NogrTL** [comment] 2020-06-26 11:29
> Sooo.... is this issue still a thing? xD
The issue is actually not in the Edge browser itself.
It's in the permissions asked for audio/video, when PC doesn't have one or both of that

I guess we can close it then

**Closed** 2020-06-26 12:04 UTC
Labels: bug, question
